---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redisOperator.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redisOperator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "redisOperator.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        {{- include "redisOperator.selectorLabels" . | nindent 8 }}
        {{- with .Values.redisOperator.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.redisOperator.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.redisOperator.imagePullSecrets | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - command:
            - /manager
          args:
            - --leader-elect
          image: "{{ .Values.redisOperator.imageName }}:{{ .Values.redisOperator.imageTag | default (printf "v%s" .Chart.AppVersion) }}"
          name: {{ .Values.redisOperator.name }}
          imagePullPolicy: {{ .Values.redisOperator.imagePullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.redisOperator.name }}-service-account
      terminationGracePeriodSeconds: 10
