{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-prometheus-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-prometheus
    release: {{ .Release.Name }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.server.scrapeInterval }}
      evaluation_interval: {{ .Values.prometheus.server.evaluationInterval }}

    rule_files:
      - "/etc/prometheus/rules/redis-alerts.yaml"

    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - {{ .Release.Name }}-alertmanager:9093
        timeout: 10s
        api_version: v2

    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name
{{- end }} 