---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name : {{ .Values.redisOperator.name }}
    helm.sh/chart : {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by : {{ .Release.Service }}
    app.kubernetes.io/instance : {{ .Release.Name }}
    app.kubernetes.io/version : {{ .Chart.AppVersion }}
    app.kubernetes.io/component: service-account
    app.kubernetes.io/part-of : {{ .Release.Name }}
  name: {{ .Values.redisOperator.name }}-service-account
  namespace: {{ .Release.Namespace }}

