---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.redis
  resources:
  - redis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.redis
  resources:
  - redis/finalizers
  verbs:
  - update
- apiGroups:
  - redis.redis
  resources:
  - redis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - redis.redis
  resources:
  - redisclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.redis
  resources:
  - redisclusters/finalizers
  verbs:
  - update
- apiGroups:
  - redis.redis
  resources:
  - redisclusters/status
  verbs:
  - get
  - patch
  - update
