apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
availabilityZones:
  - ap-northeast-2a
  - ap-northeast-2c
metadata:
  name: my-cluster
  region: ap-northeast-2
  version: "1.30"
iam:
  withOIDC: true
vpc:
  cidr: 10.10.0.0/16
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
managedNodeGroups:
  - name: default
    desiredCapacity: 3
    instanceType: t3.medium
    privateNetworking: true
