apiVersion: redis.redis/v1beta1
kind: Redis
metadata:
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis-sample
    app.kubernetes.io/part-of: redis-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: redis-operator
  name: redis-sample
spec:
  image: awbrg789/redis:latest
  port: 10000
  memory: 256mb
  resources:
    limits:
      cpu: "2"
      memory: 2000Mi
    requests:
      cpu: "2"
      memory: 2000Mi
  exporterResources:
    limits:
      cpu: "1"
      memory: 500Mi
    requests:
      cpu: "0.5"
      memory: 500Mi
