{
 "title": "Redis Operator Cluster Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(redis_up, namespace)"
    }
   },
   {
    "name": "clusterName",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(redis_up{namespace=\"$namespace\"},clusterName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Redis Total Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(redis_up{namespace=~\"$namespace\",clusterName=~\"$clusterName\"})"
    }
   ]
  },
  {
   "title": "Redis Master Node",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(redis_instance_info{namespace=~\"$namespace\",clusterName=~\"$clusterName\",role=\"master\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Connection Avg Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((redis_config_maxclients{namespace=~\"$namespace\",clusterName=~\"$clusterName\"} - redis_connected_clients{namespace=~\"$namespace\",clusterName=~\"$clusterName\"}) / redis_config_maxclients{namespace=~\"$namespace\",clusterName=~\"$clusterName\"})"
    }
   ]
  },
  {
   "title": "Redis Connections per Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_connected_clients{namespace=~\"$namespace\",clusterName=~\"$clusterName\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Redis Connected Clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_connected_clients{namespace=~\"$namespace\", clusterName=~\"$clusterName\"})"
    }
   ]
  },
  {
   "title": "Redis Slave Node",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_instance_info{namespace=~\"$namespace\",clusterName=~\"$clusterName\",role=\"master\"})"
    }
   ]
  },
  {
   "title": "Redis Commands Executed per Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(redis_commands_processed_total{namespace=~\"$namespace\",clusterName=~\"$clusterName\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Redis Command Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(irate(redis_commands_duration_seconds_total{namespace=~\"$namespace\", clusterName=\"$clusterName\"}[1m])) by (cmd)\n  /\navg(irate(redis_commands_total{namespace=~\"$namespace\",clusterName=\"$clusterName\"}[1m])) by (cmd)",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Redis Executed Commands",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "topk(5, increase(redis_commands_total{namespace=~\"$namespace\",clusterName=~\"$clusterName\"} [$__rate_interval]))",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Redis Memory Usage per Instance",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * redis_memory_used_bytes{namespace=~\"$namespace\",clusterName=\"$clusterName\"} / redis_memory_max_bytes{namespace=~\"$namespace\",clusterName=\"$clusterName\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Redis Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{namespace=~\"$namespace\",clusterName=~\"$clusterName\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Redis Input Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{namespace=~\"$namespace\",clusterName=~\"$clusterName\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Redis Output Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(redis_net_output_bytes_total{namespace=~\"$namespace\",clusterName=~\"$clusterName\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Expired / Evicted Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{namespace=~\"$namespace\",clusterName=~\"$clusterName\"}[5m]))",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{namespace=~\"$namespace\",clusterName=~\"$clusterName\"}[5m]))",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{namespace=~\"$namespace\",clusterName=~\"$clusterName\"}) - sum (redis_db_keys_expiring{namespace=~\"$namespace\",clusterName=~\"$clusterName\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{namespace=~\"$namespace\",clusterName=~\"$clusterName\"}) ",
     "legendFormat": "expiring"
    }
   ]
  }
 ]
}