apiVersion: v2
name: redis-operator
description: A Helm chart for Redis Operator
type: application
version: 0.1.2
appVersion: "0.1.2"
maintainers:
  - name: jaehanbyun
    email: awbrg789@naver.com
keywords:
  - redis
  - operator
  - kubernetes
  - prometheus
  - metrics
  - autoscaling
annotations:
  category: Database
  description: Redis Operator with Prometheus metrics and autoscaling support
dependencies:
  - name: grafana
    version: "6.56.5"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
