apiVersion: v2
name: redis-operator
description: A Helm chart for redis operator
home: https://github.com/jaehanbyun/redis-operator
sources:
  - https://github.com/jaehanbyun/redis-operator
keywords:
  - kubernetes
  - operator
  - redis
type: application
version: 0.1.0
appVersion: "0.1.0"
icon: https://github.com/jaehanbyun/redis-operator/raw/main/assets/redis-operator-logo.svg

dependencies:
  - name: prometheus
    version: "25.29.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: "8.5.*"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
