redisOperator:
  name: redis-operator
  imageName: awbrg789/redis-operator
  imagePullPolicy: Always
  imageTag: ""
  imagePullSecrets: []

replicaCount: 1

service:
  type: ClusterIP

podAnnotations: {}
podLabels: {}

podSecurityContext:
  # fsGroup: 2000

securityContext:
  # runAsNonRoot: true
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 500m
    memory: 500Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
# livenessProbe:
#   httpGet:
#     path: /
#     port: http
# readinessProbe:
#   httpGet:
#     path: /
#     port: http

nodeSelector: {}
tolerations: []
affinity: {}
